pub enum FipsArea {
    Alabama,
    Alaska,
    Arizona,
    Arkansas,
    California,
    Colorado,
    Connecticut,
    Delaware,
    DistrictOfColumbia,
    Florida,
    Georgia,
    Hawaii,
    Idaho,
    Illinois,
    Indiana,
    Iowa,
    Kansas,
    Kentucky,
    Louisiana,
    Maine,
    Maryland,
    Massachusetts,
    Michigan,
    Minnesota,
    Mississippi,
    Missouri,
    Montana,
    Nebraska,
    Nevada,
    NewHampshire,
    NewJersey,
    NewMexico,
    NewYork,
    NorthCarolina,
    NorthDakota,
    Ohio,
    Oklahoma,
    Oregon,
    Pennsylvania,
    RhodeIsland,
    SouthCarolina,
    SouthDakota,
    Tennessee,
    Texas,
    Utah,
    Vermont,
    Virginia,
    Washington,
    WestVirginia,
    Wisconsin,
    Wyoming,
    AmericanSamoa,
    Guam,
    NorthernMarianaIslands,
    PuertoRico,
    USMinorOutlyingIslands,
    USVirginIslands,
}

impl FipsArea {

    pub fn get_fips(&self) -> &str {
        use self::FipsArea::*;
        match *self {
            Alabama => "01",
            Alaska => "02",
            Arizona => "04",
            Arkansas => "05",
            California => "06",
            Colorado => "08",
            Connecticut => "09",
            Delaware => "10",
            DistrictOfColumbia => "11",
            Florida => "12",
            Georgia => "13",
            Hawaii => "15",
            Idaho => "16",
            Illinois => "17",
            Indiana => "18",
            Iowa => "19",
            Kansas => "20",
            Kentucky => "21",
            Louisiana => "22",
            Maine => "23",
            Maryland => "24",
            Massachusetts => "25",
            Michigan => "26",
            Minnesota => "27",
            Mississippi => "28",
            Missouri => "29",
            Montana => "30",
            Nebraska => "31",
            Nevada => "32",
            NewHampshire => "33",
            NewJersey => "34",
            NewMexico => "35",
            NewYork => "36",
            NorthCarolina => "37",
            NorthDakota => "38",
            Ohio => "39",
            Oklahoma => "40",
            Oregon => "41",
            Pennsylvania => "42",
            RhodeIsland => "44",
            SouthCarolina => "45",
            SouthDakota => "46",
            Tennessee => "47",
            Texas => "48",
            Utah => "49",
            Vermont => "50",
            Virginia => "51",
            Washington => "53",
            WestVirginia => "54",
            Wisconsin => "55",
            Wyoming => "56",
            AmericanSamoa => "60",
            Guam => "66",
            NorthernMarianaIslands => "69",
            PuertoRico => "72",
            USMinorOutlyingIslands => "74",
            USVirginIslands => "78",
        }
    }

    pub fn get_postal(&self) -> &str {
        use self::FipsArea::*;
        match *self {
            Alabama => "AL",
            Alaska => "AK",
            Arizona => "AZ",
            Arkansas => "AR",
            California => "CA",
            Colorado => "CO",
            Connecticut => "CT",
            Delaware => "DE",
            DistrictOfColumbia => "DC",
            Florida => "FL",
            Georgia => "GA",
            Hawaii => "HI",
            Idaho => "ID",
            Illinois => "IL",
            Indiana => "IN",
            Iowa => "IA",
            Kansas => "KS",
            Kentucky => "KY",
            Louisiana => "LA",
            Maine => "ME",
            Maryland => "MD",
            Massachusetts => "MA",
            Michigan => "MI",
            Minnesota => "MN",
            Mississippi => "MS",
            Missouri => "MO",
            Montana => "MT",
            Nebraska => "NE",
            Nevada => "NV",
            NewHampshire => "NH",
            NewJersey => "NJ",
            NewMexico => "NM",
            NewYork => "NY",
            NorthCarolina => "NC",
            NorthDakota => "ND",
            Ohio => "OH",
            Oklahoma => "OK",
            Oregon => "OR",
            Pennsylvania => "PA",
            RhodeIsland => "RI",
            SouthCarolina => "SC",
            SouthDakota => "SD",
            Tennessee => "TN",
            Texas => "TX",
            Utah => "UT",
            Vermont => "VT",
            Virginia => "VA",
            Washington => "WA",
            WestVirginia => "WV",
            Wisconsin => "WI",
            Wyoming => "WY",
            AmericanSamoa => "AS",
            Guam => "GU",
            NorthernMarianaIslands => "MP",
            PuertoRico => "PR",
            USMinorOutlyingIslands => "UM",
            USVirginIslands => "VI",
        }
    }

    pub fn get_gini(&self) -> &str {
        use self::FipsArea::*;
        match *self {
            Alabama => "01779775",
            Alaska => "01785533",
            Arizona => "01779777",
            Arkansas => "00068085",
            California => "01779778",
            Colorado => "01779779",
            Connecticut => "01779780",
            Delaware => "01779781",
            DistrictOfColumbia => "01702382",
            Florida => "00294478",
            Georgia => "01705317",
            Hawaii => "01779782",
            Idaho => "01779783",
            Illinois => "01779784",
            Indiana => "00448508",
            Iowa => "01779785",
            Kansas => "00481813",
            Kentucky => "01779786",
            Louisiana => "01629543",
            Maine => "01779787",
            Maryland => "01714934",
            Massachusetts => "00606926",
            Michigan => "01779789",
            Minnesota => "00662849",
            Mississippi => "01779790",
            Missouri => "01779791",
            Montana => "00767982",
            Nebraska => "01779792",
            Nevada => "01779793",
            NewHampshire => "01779794",
            NewJersey => "01779795",
            NewMexico => "00897535",
            NewYork => "01779796",
            NorthCarolina => "01027616",
            NorthDakota => "01779797",
            Ohio => "01085497",
            Oklahoma => "01102857",
            Oregon => "01155107",
            Pennsylvania => "01779798",
            RhodeIsland => "01219835",
            SouthCarolina => "01779799",
            SouthDakota => "01785534",
            Tennessee => "01325873",
            Texas => "01779801",
            Utah => "01455989",
            Vermont => "01779802",
            Virginia => "01779803",
            Washington => "01779804",
            WestVirginia => "01779805",
            Wisconsin => "01779806",
            Wyoming => "01779807",
            AmericanSamoa => "01802701",
            Guam => "01802705",
            NorthernMarianaIslands => "01779809",
            PuertoRico => "01779808",
            USMinorOutlyingIslands => "01878752",
            USVirginIslands => "01802710",
        }
    }
}

